data:
  image: busybox
  volumes:
    - /data

db:
  image: postgres:9.4
  volumes_from:
    - data
  ports:
    - "5432:5432"

api:
  image: node:wheezy
  volumes:
    - ./api:/app
  working_dir: /app
  links:
   - db
  ports:
    - "8000:8000"
  environment:
    HOST: "0.0.0.0"
    PORT: "8000"
    DB_DATABASE: postgres
    DB_USERNAME: postgres
  command: npm run watch
